### PR TITLE
Mileston1 mainsection

### PR DESCRIPTION
**Pull request by Abdona**
The Next Web Prema Clone. we have used flex and grid to organize the webpage contents.

### CODE REVIEW

**Review by MuriloRoque — CHANGES_REQUESTED** [review]
## Status: Changes requested :red_circle: 

### Hello @Abdona and @verissimohenry :wave: 

### You have started this milestone really well, I will give you that! Your page is well structured, and it looks like all of the sections are there. We only have a few issues to address before moving on, so please check my comments below:

- [x] It looks like your images are not being loaded properly, and it might be because you are accessing an URL directly, and it's being blocked. I know it might work locally, but it's not a good practice to use them like this to host your webpage on Github Pages. Can you please solve this issue? :smile: 

Screenshot from 2021-03-03 06-35-07

- [x] Your footer elements are not correctly aligned, they should be centered like the original webpage, please take a look below and fix it:

Screenshot from 2021-03-03 06-35-20

Kindly make the requested changes and submit them for another review, please :pray: 

I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Comment by Abdona** [comment]
> ## Status: Changes requested 
> ### Hello @Abdona and @verissimohenry 
> ### You have started this milestone really well, I will give you that! Your page is well structured, and it looks like all of the sections are there. We only have a few issues to address before moving on, so please check my comments below:
> * [x]  It looks like your images are not being loaded properly, and it might be because you are accessing an URL directly, and it's being blocked. I know it might work locally, but it's not a good practice to use them like this to host your webpage on Github Pages. Can you please solve this issue? smile
> 
> Screenshot from 2021-03-03 06-35-07
> 
> * [x]  Your footer elements are not correctly aligned, they should be centered like the original webpage, please take a look below and fix it:
> 
> Screenshot from 2021-03-03 06-35-20
> 
> Kindly make the requested changes and submit them for another review, please 
> 
> I will be on Slack 24/7 in case you have any questions about this review 
> 
> Murilo Roque Paiva da Silva
> 
> * Github: [@muriloroque](https://github.com/MuriloRoque)
> * Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)
> 
> [Twitter Follow](https://twitter.com/MuriloRoquePai1)

Thank you for your notices and review.I have fixed the error and resubmitted the project.

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required 🛑♻**

<hr>

Hello there, great work you've done so far on this project. 🎉👌👍

1. Linters are well configured.
2. Very decent README file.
3. Organized and clean code.
4. Media queries are correctly set up.
4. Well done making the project almost the same as the original page.

However, there are still a few more changes to implement in order to get this PR approved 😊🙏 Please read my comments below.

## **Header**

- [ ] Please use header tag instead of section tag in the HTML file.

## **Highlights (the 3 articles)**

- [ ] The title of each article should have a link (a tag) inside of it.
- [ ] In "Tablet mode". The first article's title should appear bigger than the desktop mode.
- [ ] In "Desktop mode". The TWN logo appears over the first article, at the top left corner.
- [ ] In "Desktop mode". There is a red overlay with a gradient in the top half of the first article.
- [ ] In "Desktop mode". The date appears over the first article, at the top right corner.

## **Latest Funding Section**

- [x] The title of the whole section, the list below items, each article's title, the two categories, and the final text below should have (a tag) in all of them. Please make the href attribute within each (a tag) in the HTML file and make it equal to "=".
- [ ] The list below the section's title should be grouped within a (nav tag)
- [ ] In "Tablet mode". The nav menu is below the title, and the options are aligned in a row, separated by |. i.e. option1 | option2 | option 3
- [ ] In "Desktop mode". The nav menu is to the left of the main title, and the options are aligned in a row separated by | like the tablet mode.

## **Footer**

- [ ] Each link (item) in the footer should have (a tag)
- [x] The two menus should be exactly centered below each other.
- [x] Please fix the white gap at the bottom of the page. The copyright text is hard to see as well as the logo at the end.

## **General**

- [ ] **REQUIRED**. Please fix the images on the live demo link.

- **OPTIONAL**. Please consider using the header tag only for the header of the page, not as a header of a section or a single article within the page. Using semantic HTML tags is one of the most important and professional thing to notice about a programmer :)

<hr>

Please do the above changes and ask for another review. Good luck and happy coding 👨‍💻💻

<hr>

Feel free to contact me on Slack with the name "Mahmoud Bakr" if you have any questions regarding my comments. 😊👍

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required 🛑♻**

<hr>

Hello there, good job working on the requested changes. However, I'm afraid you've missed some of them. Please follow my comments below.

- [ ] Each article's main title should have a (a tag). Please see the top 3 articles' titles and make a (a tag) inside of each one of them
- [x] Each nav item (link) in the footer should be a (a tag). The social links and the other nav menu which is (Events, About, Advertise, etc)
- [x] The "Latest Funding" section contains 4 articles, each one of them has a title, this title should be wrapped inside of it (a tag), not the whole div inside a tag as it currently is.
- [x] The TWN logo appears over the first article, at the top left corner (In Desktop Screen Size)
- [x] There is a red overlay with a gradient in the top half of the first article. (In Desktop Screen Size)
- [x] The date appears over the first article, at the top right corner. (In Desktop Screen Size)
- [ ] The nav menu is to the left of the main title, and the options are aligned in a row, separated by |. (In Desktop Screen Size), (The Latest Funding Section)
- [ ] The nav menu is below the main title, and the options are aligned in a row, separated by |. (In Tablet Screen Size), (The latest funding section)

<hr>

Please make sure to apply all of the required changes and ask for another review. :)
Good luck and happy coding. 👨‍💻💻

**Review by mahmoud717 — APPROVED** [review]
### STATUS: APPROVED ✔️ ✔️ 

**hi guys**

**Great job with making all of the requirements. the project is approved, you can go ahead and merge this pull request**

**Pull request merged**
